version: 0.2

env:
  variables:
    AWS_REGION: us-east-1
    IMAGE_TAG: latest
    ECR_REPO: 029197504624.dkr.ecr.us-east-1.amazonaws.com/my-java-app

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "✅ Installing dependencies..."
      - echo "Java version:"
      - java -version
      - echo "Maven version:"
      - mvn -v

  pre_build:
    commands:
      - echo "🔐 Logging into Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO
      - echo "📦 Building Spring Boot JAR file..."
      - mvn clean package -DskipTests
      - cp target/*.jar target/app.jar  # Dockerfile uses app.jar

  build:
    commands:
      - echo "🐳 Building Docker image..."
      - docker build -t $ECR_REPO:$IMAGE_TAG .

  post_build:
    commands:
      - echo "📤 Pushing Docker image to ECR..."
      - docker push $ECR_REPO:$IMAGE_TAG
      - echo "📁 Preparing CodeDeploy files..."
      - sed -i "s|IMAGE_URI|$ECR_REPO:$IMAGE_TAG|g" taskdef.json
      - echo "✅ Creating artifact archive..."
      - zip -r deploy.zip appspec.yaml taskdef.json

artifacts:
  files:
    - deploy.zip
    - appspec.yaml
    - taskdef.json
