version: 0.2

phases:
  pre_build:
    commands:
      - echo 🔧 Installing dependencies...
      - yum install -y jq maven
      - echo 🔐 Logging into Amazon ECR...
      - ACCOUNT_ID=029197504624
      - REGION=us-east-1
      - REPO_NAME=my-java-app
      - IMAGE_TAG=latest
      - ECR_URI=$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPO_NAME
      - aws --version
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com

  build:
    commands:
      - echo 🛠️ Building the Spring Boot JAR...
      - mvn clean package -DskipTests
      - cp target/*.jar target/app.jar
      - echo 🐳 Building the Docker image...
      - docker build -t $REPO_NAME .
      - docker tag $REPO_NAME:$IMAGE_TAG $ECR_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo 📤 Pushing Docker image to ECR...
      - docker push $ECR_URI:$IMAGE_TAG
      - echo 📝 Writing imagedefinitions.json...
      - printf '[{"name":"my-java-app","imageUri":"%s"}]' $ECR_URI:$IMAGE_TAG > imagedefinitions.json
      - echo ✅ Build completed successfully

artifacts:
  files:
    - imagedefinitions.json
    - appspec.yml
